/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch Design System - Neural Noir tokens
        "background": "#0e0e13",
        "surface": "#0e0e13",
        "surface-dim": "#0e0e13",
        "surface-bright": "#2c2b33",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#131319",
        "surface-container": "#19191f",
        "surface-container-high": "#1f1f26",
        "surface-container-highest": "#25252d",
        "surface-variant": "#25252d",
        "surface-tint": "#a8a4ff",
        "on-background": "#f9f5fd",
        "on-surface": "#f9f5fd",
        "on-surface-variant": "#acaab1",
        "primary": "#a8a4ff",
        "primary-dim": "#665bff",
        "primary-container": "#9995ff",
        "primary-fixed": "#9995ff",
        "primary-fixed-dim": "#8a85ff",
        "on-primary": "#1f009e",
        "on-primary-fixed": "#000000",
        "on-primary-container": "#16007d",
        "on-primary-fixed-variant": "#1d0098",
        "secondary": "#aa8ffd",
        "secondary-dim": "#a88cfa",
        "secondary-container": "#4e329b",
        "secondary-fixed": "#d8caff",
        "secondary-fixed-dim": "#cbbaff",
        "on-secondary": "#290071",
        "on-secondary-container": "#d7c8ff",
        "on-secondary-fixed": "#3b1a87",
        "on-secondary-fixed-variant": "#583da5",
        "tertiary": "#ff9dcf",
        "tertiary-dim": "#eb7bb8",
        "tertiary-container": "#fb88c6",
        "tertiary-fixed": "#fe8bc9",
        "tertiary-fixed-dim": "#ee7ebb",
        "on-tertiary": "#6c0f4c",
        "on-tertiary-container": "#5e0041",
        "on-tertiary-fixed": "#360023",
        "on-tertiary-fixed-variant": "#6d104c",
        "outline": "#76747b",
        "outline-variant": "#48474d",
        "error": "#ff6e84",
        "error-dim": "#d73357",
        "error-container": "#a70138",
        "on-error": "#490013",
        "on-error-container": "#ffb2b9",
        "inverse-surface": "#fcf8ff",
        "inverse-on-surface": "#55545b",
        "inverse-primary": "#4c38fd",
        // Legacy nn.* namespace for admin pages
        nn: {
          bg: '#0e0e13',
          surface: '#0e0e13',
          'surface-low': '#131319',
          'surface-container': '#19191f',
          'surface-high': '#1f1f26',
          'surface-highest': '#25252d',
          'surface-lowest': '#000000',
          primary: '#a8a4ff',
          'primary-dim': '#665bff',
          'primary-brand': '#3713ec',
          secondary: '#aa8ffd',
          tertiary: '#ff9dcf',
          'tertiary-dim': '#eb7bb8',
          'on-surface': '#f9f5fd',
          'on-surface-variant': '#acaab1',
          outline: '#76747b',
          'outline-variant': '#48474d',
          error: '#ff6e84',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'float': 'float 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
